apiVersion: v2
name: infra
description: IVISS Infrastructure — ServiceAccount, ExternalSecrets, static secrets
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://iviss.cloud/favicon.ico
keywords:
  - iviss
  - infrastructure
  - secrets
sources:
  - https://github.com/skyengpro/iviss