global:
  environment: production

nameOverride: ""
fullnameOverride: "iviss-infra"

secrets:
  adminBootstrap:
    email: admin@iviss.cloud
    phone: "+237600000000"
    username: admin
  smsProvider: vonage
  emailProvider: mock
  otpViaEmail: "true"

externalSecrets:
  refreshInterval: 1h