global:
  environment: production
  domainName: iviss.example.com
  imageTag: ""
  imagePullPolicy: Always

nameOverride: ""
fullnameOverride: "iviss-frontend"

replicas: 2

image:
  repository: ghcr.io/skyengpro/iviss/frontend
  tag: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuUtilization: 70
  memoryUtilization: 80

config:
  viteApiUrl: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "100"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: dev.iviss.skyengpro.app
      paths:
        - /
  tls:
    - hosts:
        - dev.iviss.skyengpro.app
      secretName: iviss-frontend-tls