global:
  domainName: dev.iviss.skyengpro.app
  imageTag: latest

replicas: 3

hpa:
  minReplicas: 3
  maxReplicas: 10

config:
  viteApiUrl: "https://dev.iviss.skyengpro.app"

ingress:
  hosts:
    - host: dev.iviss.skyengpro.app
      paths:
        - /
  tls:
    - hosts:
        - dev.iviss.skyengpro.app
      secretName: iviss-frontend-tls