global:
  environment: production
  imageTag: latest

replicas: 3

hpa:
  minReplicas: 3
  maxReplicas: 10

ingress:
  hosts:
    - host: prod.iviss.skyengpro.app
      paths:
        - /
  tls:
    - hosts:
        - prod.iviss.skyengpro.app
      secretName: iviss-frontend-tls