global:
  domainName: prod.iviss.skyengpro.app
  imageTag: latest

replicas: 3

hpa:
  minReplicas: 3
  maxReplicas: 10

config:
  viteApiUrl: "https://prod.iviss.skyengpro.app"

ingress:
  hosts:
    - host: prod.iviss.skyengpro.app
      paths:
        - /
  tls:
    - hosts:
        - prod.iviss.skyengpro.app
      secretName: iviss-frontend-tls