-- no-transaction
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'USER_DELETED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'SESSION_TERMINATED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'SESSION_RESTARTED';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'ACTIVATION_CODE_RESENT';
