apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
{{- if .Values.config.viteApiUrl }}
  VITE_API_URL: {{ .Values.config.viteApiUrl | quote }}
{{- end }}