---
- include_tasks: setup.yml
- include_tasks: ssl.yml
  when:
    - domain_name is defined
    - certbot_email is defined
    - not (cloudfront_enabled | default(false) | bool)
- include_tasks: deploy.yml
