---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
      - ufw
      - nginx
      - certbot
      - python3-certbot-nginx
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-docker
    state: present


- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Configure UFW
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - 443

- name: Enable UFW
  ufw:
    state: enabled

- name: Check if swap file exists
  stat:
    path: /swapfile
  register: swap_stat

- name: Create swap file (4GB)
  command: "{{ item }}"
  with_items:
    - fallocate -l 4G /swapfile
    - chmod 600 /swapfile
    - mkswap /swapfile
    - swapon /swapfile
  when: not swap_stat.stat.exists
  ignore_errors: yes

- name: Add swap to fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^/swapfile'
    line: '/swapfile none swap sw 0 0'
    state: present

- name: Create app directory
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"

- name: Check if Nginx config exists
  stat:
    path: /etc/nginx/sites-available/iviss
  register: nginx_conf_stat
  when: domain_name is defined

- name: Check if Nginx config is managed by Certbot
  command: grep -q "managed by Certbot" /etc/nginx/sites-available/iviss
  register: certbot_check
  ignore_errors: yes
  changed_when: false
  when: 
    - domain_name is defined
    - nginx_conf_stat.stat.exists

- name: Deploy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/iviss
    mode: '0644'
  when: 
    - domain_name is defined

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/iviss
    dest: /etc/nginx/sites-enabled/iviss
    state: link
  when: domain_name is defined

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  when: domain_name is defined
