---
- name: Check if certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: cert_stat

- name: Obtain SSL certificate
  command: >
    certbot --nginx
    --staging
    -d {{ domain_name }}
    --non-interactive
    --agree-tos
    --email {{ certbot_email }}
  when: not cert_stat.stat.exists
