---
- name: Check if certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: cert_stat

- name: Obtain SSL certificate
  command: >
    certbot --nginx
    --server https://acme.zerossl.com/v2/DV90
    # Use Buypass if ZeroSSL EAB is a hassle:
    # --server https://acme.buypass.com/acme/directory
    -d {{ domain_name }}
    --non-interactive
    --agree-tos
    --email {{ certbot_email }}
  when: not cert_stat.stat.exists
