---
- name: Check if certificate exists
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  register: cert_stat

- name: Remove stale Certbot locks
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/letsencrypt/.certbot.lock
    - /tmp/certbot.lock
  ignore_errors: yes

- name: Obtain SSL certificate
  command: >
    certbot --nginx
    -d {{ domain_name }}
    --non-interactive
    --agree-tos
    --email {{ certbot_email }}
  register: certbot_obtain
  until: certbot_obtain is success
  retries: 2
  delay: 5
  when: not cert_stat.stat.exists
  ignore_errors: yes

- name: Obtain SSL certificate (Retry without email if registration failed)
  command: >
    certbot --nginx
    -d {{ domain_name }}
    --non-interactive
    --agree-tos
    --register-unsafely-without-email
  when: 
    - not cert_stat.stat.exists
    - certbot_obtain is failed

- name: Check if Nginx config is missing SSL lines
  command: grep -q "managed by Certbot" /etc/nginx/sites-available/iviss
  register: fresh_certbot_check
  ignore_errors: yes
  changed_when: false
  when: 
    - domain_name is defined
    - cert_stat.stat.exists

- name: Re-apply Certbot configuration if missing from Nginx
  command: >
    certbot install --nginx
    -d {{ domain_name }}
    --cert-name {{ domain_name }}
    --non-interactive
  when: 
    - domain_name is defined
    - cert_stat.stat.exists
    - fresh_certbot_check.rc is defined and fresh_certbot_check.rc != 0
