apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iviss
  namespace: argocd
spec:
  description: IVISS application project
  sourceRepos:
    - https://github.com/skyengpro/iviss
  destinations:
    - namespace: iviss
      server: https://kubernetes.default.svc
    - namespace: iviss-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
  orphanedResources:
    warn: true
