apiVersion: v1
kind: Secret
metadata:
  name: iviss-postgres-superuser
  namespace: iviss
  labels:
    app.kubernetes.io/part-of: iviss
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: REPLACE_ME_GENERATED_SUPERUSER_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: iviss-postgres-app
  namespace: iviss
  labels:
    app.kubernetes.io/part-of: iviss
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
  username: iviss_user
  password: REPLACE_ME_GENERATED_APP_PASSWORD