apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iviss-vehicle-api-keys
  namespace: iviss
  labels:
    app.kubernetes.io/part-of: iviss
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: iviss-secrets
    creationPolicy: Merge
    template:
      type: Opaque
      data:
        EXTERNAL_API_BASE_URL: "{{ .external_api_base_url }}"
        EXTERNAL_API_USERNAME: "{{ .external_api_username }}"
        EXTERNAL_API_PASSWORD: "{{ .external_api_password }}"
        EXTERNAL_API_LOCK_NDIA: "{{ .external_api_lock_ndia }}"
        EXTERNAL_API_KINDIA: "{{ .external_api_kindia }}"
        EXTERNAL_API_USER: "{{ .external_api_user }}"
        EXTERNAL_API_CLIENT: "{{ .external_api_client }}"
        EXTERNAL_API_CTR: "{{ .external_api_ctr }}"
        EXTERNAL_API_TLS_CERT_B64: "{{ .external_api_tls_cert_b64 }}"
  data:
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_base_url
      secretKey: external_api_base_url
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_username
      secretKey: external_api_username
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_password
      secretKey: external_api_password
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_lock_ndia
      secretKey: external_api_lock_ndia
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_kindia
      secretKey: external_api_kindia
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_user
      secretKey: external_api_user
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_client
      secretKey: external_api_client
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_ctr
      secretKey: external_api_ctr
    - remoteRef:
        key: iviss/prod/vehicle-api-keys
        property: external_api_tls_cert_b64
      secretKey: external_api_tls_cert_b64