apiVersion: v1
kind: Secret
metadata:
  name: iviss-static-secrets
  namespace: iviss
  labels:
    app.kubernetes.io/part-of: iviss
type: Opaque
stringData:
  ADMIN_BOOTSTRAP_EMAIL: "admin@iviss.cloud"
  ADMIN_BOOTSTRAP_PHONE: "+237600000000"
  ADMIN_BOOTSTRAP_USERNAME: "admin"
  SMS_PROVIDER: "vonage"
  EMAIL_PROVIDER: "mock"
  OTP_VIA_EMAIL: "true"