global:
  environment: production
  domainName: dev.iviss.skyengpro.app
  imageTag: latest

replicas: 3

hpa:
  minReplicas: 3
  maxReplicas: 10

config:
  environment: production
  logLevel: info
  smsProvider: vonage
  emailProvider: resend
  otpViaEmail: true

ingress:
  hosts:
    - host: dev.iviss.skyengpro.app
      paths:
        - /api(/|$)(.*)
        - /api-doc(/|$)(.*)
  tls:
    - hosts:
        - dev.iviss.skyengpro.app
      secretName: iviss-api-tls