apiVersion: v1
kind: Secret
metadata:
  name: iviss-postgres-superuser
  namespace: iviss
  labels:
    {{- include "database.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.cnpg.superuserPassword | default (randAlphaNum 32) | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: iviss-postgres-app
  namespace: iviss
  labels:
    {{- include "database.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    cnpg.io/reload: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.owner | quote }}
  password: {{ .Values.cnpg.appPassword | default (randAlphaNum 32) | quote }}