apiVersion: v1
kind: Secret
metadata:
  name: iviss-static-secrets
  namespace: iviss
  labels:
    {{- include "database.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
  ADMIN_BOOTSTRAP_EMAIL: {{ .Values.secrets.adminBootstrap.email | quote }}
  ADMIN_BOOTSTRAP_PHONE: {{ .Values.secrets.adminBootstrap.phone | quote }}
  ADMIN_BOOTSTRAP_USERNAME: {{ .Values.secrets.adminBootstrap.username | quote }}
  SMS_PROVIDER: {{ .Values.secrets.smsProvider | quote }}
  EMAIL_PROVIDER: {{ .Values.secrets.emailProvider | quote }}
  OTP_VIA_EMAIL: {{ .Values.secrets.otpViaEmail | quote }}