apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iviss.fullname" . }}-config
  labels:
    {{- include "iviss.labels" . | nindent 4 }}
data:
  SERVER_HOST: {{ .Values.backend.config.serverHost | quote }}
  SERVER_PORT: {{ .Values.backend.config.serverPort | quote }}
  LOG_LEVEL: {{ .Values.backend.config.logLevel | quote }}
  ENVIRONMENT: {{ .Values.backend.config.environment | quote }}
  SHIFT_START_HOUR: {{ .Values.backend.config.shiftStartHour | quote }}
  SHIFT_END_HOUR: {{ .Values.backend.config.shiftEndHour | quote }}
  SMS_PROVIDER: {{ .Values.backend.config.smsProvider | quote }}
  EMAIL_PROVIDER: {{ .Values.backend.config.emailProvider | quote }}
  OTP_VIA_EMAIL: {{ .Values.backend.config.otpViaEmail | quote }}
  RESEND_FROM_EMAIL: {{ .Values.backend.config.resendFromEmail | quote }}
  SMTP_HOST: {{ .Values.backend.config.smtpHost | quote }}
  SMTP_PORT: {{ .Values.backend.config.smtpPort | quote }}
  SMTP_USERNAME: {{ .Values.backend.config.smtpUsername | quote }}
  SQLX_OFFLINE: "true"
{{- if .Values.frontend.config.viteApiUrl }}
  VITE_API_URL: {{ .Values.frontend.config.viteApiUrl | quote }}
{{- end }}
