// This file is auto-generated by @hey-api/openapi-ts

export const ActionTypeSchema = {
    type: 'string',
    enum: [
        'check',
        'flag',
        'citation',
        'impound',
        'release'
    ]
} as const;

export const ActivateRequestSchema = {
    type: 'object',
    required: [
        'badgeId',
        'activationCode',
        'deviceId',
        'publicKeyBase64'
    ],
    properties: {
        activationCode: {
            type: 'string'
        },
        badgeId: {
            type: 'string'
        },
        deviceId: {
            type: 'string',
            format: 'uuid'
        },
        publicKeyBase64: {
            type: 'string'
        }
    }
} as const;

export const ActivateResponseSchema = {
    type: 'object',
    required: [
        'accessToken',
        'refreshToken',
        'user'
    ],
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/UserProfile'
        }
    }
} as const;

export const ActivityDataSchema = {
    type: 'object',
    required: [
        'hour',
        'count'
    ],
    properties: {
        count: {
            type: 'integer',
            format: 'int64'
        },
        hour: {
            type: 'string'
        }
    }
} as const;

export const ActivityFeedItemDtoSchema = {
    type: 'object',
    required: [
        'id',
        'plateNumber',
        'overallStatus',
        'createdAt',
        'agentName'
    ],
    properties: {
        agentName: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        overallStatus: {
            type: 'string'
        },
        plateNumber: {
            type: 'string'
        }
    }
} as const;

export const ActivityFeedResponseSchema = {
    type: 'object',
    required: [
        'items'
    ],
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ActivityFeedItemDto'
            }
        }
    }
} as const;

export const AgentLocationDtoSchema = {
    type: 'object',
    required: [
        'agentId',
        'agentName',
        'latitude',
        'longitude',
        'lastUpdated'
    ],
    properties: {
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        agentName: {
            type: 'string'
        },
        lastUpdated: {
            type: 'string'
        },
        latitude: {
            type: 'number',
            format: 'double'
        },
        longitude: {
            type: 'number',
            format: 'double'
        }
    }
} as const;

export const AppErrorResponseSchema = {
    type: 'object',
    required: [
        'code',
        'message'
    ],
    properties: {
        code: {
            $ref: '#/components/schemas/ErrorCode'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const AuthResponseSchema = {
    type: 'object',
    required: [
        'accessToken',
        'refreshToken',
        'user'
    ],
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        },
        user: {
            $ref: '#/components/schemas/UserProfile'
        }
    }
} as const;

export const ControlActionSchema = {
    type: 'object',
    required: [
        'action_type',
        'timestamp'
    ],
    properties: {
        action_type: {
            $ref: '#/components/schemas/ActionType'
        },
        description: {
            type: 'string',
            nullable: true
        },
        timestamp: {
            type: 'string'
        }
    }
} as const;

export const ControlActivityPointSchema = {
    type: 'object',
    required: [
        'label',
        'count'
    ],
    properties: {
        count: {
            type: 'integer',
            format: 'int64'
        },
        label: {
            type: 'string'
        }
    }
} as const;

export const ControlActivityResponseSchema = {
    type: 'object',
    required: [
        'range',
        'series'
    ],
    properties: {
        range: {
            $ref: '#/components/schemas/DashboardRange'
        },
        series: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ControlActivityPoint'
            }
        }
    }
} as const;

export const ControlLocationSchema = {
    type: 'object',
    properties: {
        address: {
            type: 'string',
            nullable: true
        },
        latitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        longitude: {
            type: 'number',
            format: 'double',
            nullable: true
        }
    }
} as const;

export const ControlResultsSchema = {
    type: 'object',
    required: [
        'registration',
        'insurance',
        'technical_inspection',
        'wanted_status',
        'customs_status'
    ],
    properties: {
        customs_status: {
            $ref: '#/components/schemas/Status'
        },
        insurance: {
            $ref: '#/components/schemas/Status'
        },
        registration: {
            $ref: '#/components/schemas/Status'
        },
        technical_inspection: {
            $ref: '#/components/schemas/Status'
        },
        wanted_status: {
            $ref: '#/components/schemas/Status'
        }
    }
} as const;

export const CreateControlRequestSchema = {
    type: 'object',
    required: [
        'plate_number',
        'agent_id',
        'organization_id',
        'identification_mode',
        'results'
    ],
    properties: {
        address: {
            type: 'string',
            nullable: true
        },
        agent_id: {
            type: 'string',
            format: 'uuid'
        },
        identification_mode: {
            $ref: '#/components/schemas/IdentificationMode'
        },
        latitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        longitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        notes: {
            type: 'string',
            nullable: true
        },
        ocr_confidence: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        organization_id: {
            type: 'string',
            format: 'uuid'
        },
        plate_number: {
            type: 'string'
        },
        results: {
            $ref: '#/components/schemas/ControlResults'
        }
    }
} as const;

export const CreateControlResponseSchema = {
    type: 'object',
    required: [
        'id',
        'message'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        message: {
            type: 'string'
        }
    }
} as const;

export const CreatePendingSubmissionRequestSchema = {
    type: 'object',
    description: 'Request payload for creating a new pending submission',
    required: [
        'plateNumber',
        'agentId',
        'frontImageUrl',
        'backImageUrl'
    ],
    properties: {
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        backImageUrl: {
            type: 'string'
        },
        frontImageUrl: {
            type: 'string'
        },
        latitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        longitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        notes: {
            type: 'string',
            nullable: true
        },
        plateNumber: {
            type: 'string'
        }
    }
} as const;

export const CustomsStatusSchema = {
    type: 'object',
    required: [
        'status',
        'is_cleared'
    ],
    properties: {
        declaration_number: {
            type: 'string',
            nullable: true
        },
        import_date: {
            type: 'string',
            nullable: true
        },
        is_cleared: {
            type: 'boolean'
        },
        notes: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status'
        }
    }
} as const;

export const DashboardRangeSchema = {
    type: 'string',
    enum: [
        '24h',
        '7d',
        '30d'
    ]
} as const;

export const DashboardStatsSchema = {
    type: 'object',
    required: [
        'todayControls',
        'activeAlerts',
        'totalVehicles',
        'onlineAgents',
        'pendingSubmissions',
        'organizationsCount',
        'activity24h',
        'liveAgents'
    ],
    properties: {
        activeAlerts: {
            type: 'integer',
            format: 'int64'
        },
        activity24h: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ActivityData'
            }
        },
        liveAgents: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AgentLocationDto'
            }
        },
        onlineAgents: {
            type: 'integer',
            format: 'int64'
        },
        organizationsCount: {
            type: 'integer',
            format: 'int64'
        },
        pendingSubmissions: {
            type: 'integer',
            format: 'int64'
        },
        todayControls: {
            type: 'integer',
            format: 'int64'
        },
        totalVehicles: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const DataEntryResponseSchema = {
    type: 'object',
    description: 'Response after approved and enters vehicle data',
    required: [
        'message',
        'submission_id',
        'plate_number'
    ],
    properties: {
        message: {
            type: 'string'
        },
        plate_number: {
            type: 'string',
            description: 'Plate number that was added to the external registry'
        },
        submission_id: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const DeviceStatusSchema = {
    type: 'string',
    enum: [
        'PENDING',
        'ACTIVE',
        'INACTIVE',
        'REVOKED',
        'SUSPENDED'
    ]
} as const;

export const ErrorCodeSchema = {
    type: 'string',
    enum: [
        'UNAUTHORIZED',
        'FORBIDDEN',
        'DATABASE_ERROR',
        'NOT_FOUND',
        'BAD_REQUEST',
        'TOO_MANY_REQUESTS',
        'EXTERNAL_API_FAILURE',
        'INTERNAL_ERROR'
    ]
} as const;

export const IdentificationModeSchema = {
    type: 'string',
    description: 'How the plate was identified by the agent',
    enum: [
        'manual',
        'photo',
        'live'
    ]
} as const;

export const ImageUploadRequestSchema = {
    type: 'object',
    required: [
        'image'
    ],
    properties: {
        image: {
            type: 'string',
            format: 'binary'
        }
    }
} as const;

export const InsuranceStatusSchema = {
    type: 'object',
    required: [
        'status'
    ],
    properties: {
        coverage_type: {
            type: 'string',
            nullable: true
        },
        expiry_date: {
            type: 'string',
            nullable: true
        },
        notes: {
            type: 'string',
            nullable: true
        },
        policy_number: {
            type: 'string',
            nullable: true
        },
        provider: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status'
        }
    }
} as const;

export const ListControlResponseSchema = {
    type: 'object',
    required: [
        'id',
        'plate_number',
        'agent_id',
        'organization_id',
        'timestamp',
        'status',
        'identification_mode',
        'location',
        'results',
        'actions'
    ],
    properties: {
        actions: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ControlAction'
            }
        },
        agent_id: {
            type: 'string',
            format: 'uuid'
        },
        agent_name: {
            type: 'string',
            nullable: true
        },
        confidence: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        identification_mode: {
            $ref: '#/components/schemas/IdentificationMode'
        },
        location: {
            $ref: '#/components/schemas/ControlLocation'
        },
        notes: {
            type: 'string',
            nullable: true
        },
        organization_id: {
            type: 'string',
            format: 'uuid'
        },
        plate_number: {
            type: 'string'
        },
        results: {
            $ref: '#/components/schemas/ControlResults'
        },
        status: {
            $ref: '#/components/schemas/Status'
        },
        timestamp: {
            type: 'string'
        },
        vehicle: {
            allOf: [
                {
                    $ref: '#/components/schemas/VehicleInfo'
                }
            ],
            nullable: true
        }
    }
} as const;

export const LoginRequestSchema = {
    type: 'object',
    required: [
        'email',
        'password'
    ],
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const OrganizationSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'orgType'
    ],
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        orgType: {
            $ref: '#/components/schemas/OrganizationType'
        },
        region: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const OrganizationTypeSchema = {
    type: 'string',
    enum: [
        'police',
        'customs',
        'bordercontrol',
        'other'
    ]
} as const;

export const OwnerInfoSchema = {
    type: 'object',
    required: [
        'name'
    ],
    properties: {
        address: {
            type: 'string',
            nullable: true
        },
        name: {
            type: 'string'
        },
        national_id: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const PagedControlsResponseSchema = {
    type: 'object',
    required: [
        'items',
        'total',
        'page',
        'page_size'
    ],
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/ListControlResponse'
            }
        },
        page: {
            type: 'integer',
            format: 'int64'
        },
        page_size: {
            type: 'integer',
            format: 'int64'
        },
        total: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const PendingSubmissionListItemSchema = {
    type: 'object',
    description: 'Lightweight list item for admin dashboard',
    required: [
        'id',
        'plate_number',
        'status',
        'submitted_at'
    ],
    properties: {
        agent_name: {
            type: 'string',
            nullable: true
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        plate_number: {
            type: 'string'
        },
        status: {
            $ref: '#/components/schemas/SubmissionStatus'
        },
        submitted_at: {
            type: 'string'
        }
    }
} as const;

export const PendingSubmissionRequestSchema = {
    type: 'object',
    description: 'Detailed view of a pending submission (for admin review)',
    required: [
        'id',
        'plate_number',
        'agent_id',
        'front_image_url',
        'back_image_url',
        'status',
        'submitted_at'
    ],
    properties: {
        admin_note: {
            type: 'string',
            nullable: true
        },
        agent_id: {
            type: 'string',
            format: 'uuid'
        },
        agent_name: {
            type: 'string',
            nullable: true
        },
        back_image_url: {
            type: 'string',
            description: 'URL or Base64 of back image'
        },
        front_image_url: {
            type: 'string',
            description: 'URL or Base64 of front image'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        location: {
            allOf: [
                {
                    $ref: '#/components/schemas/SubmissionLocation'
                }
            ],
            nullable: true
        },
        notes: {
            type: 'string',
            nullable: true
        },
        plate_number: {
            type: 'string'
        },
        reviewed_at: {
            type: 'string',
            nullable: true
        },
        reviewed_by: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/SubmissionStatus'
        },
        submitted_at: {
            type: 'string'
        }
    }
} as const;

export const PoliceStatusSchema = {
    type: 'object',
    required: [
        'status',
        'is_wanted',
        'is_stolen'
    ],
    properties: {
        is_stolen: {
            type: 'boolean'
        },
        is_wanted: {
            type: 'boolean'
        },
        notes: {
            type: 'string',
            nullable: true
        },
        report_date: {
            type: 'string',
            nullable: true
        },
        report_number: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status'
        }
    }
} as const;

export const ProvisionUserRequestSchema = {
    type: 'object',
    description: 'Request for POST /admin/users (provisioning)',
    required: [
        'username',
        'phoneNumber',
        'fullName',
        'role',
        'organizationId'
    ],
    properties: {
        badgeId: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        fullName: {
            type: 'string'
        },
        organizationId: {
            type: 'string',
            format: 'uuid'
        },
        phoneNumber: {
            type: 'string'
        },
        role: {
            $ref: '#/components/schemas/UserRole'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const RecentAlertItemDtoSchema = {
    type: 'object',
    required: [
        'id',
        'plateNumber',
        'overallStatus',
        'createdAt',
        'agentName'
    ],
    properties: {
        address: {
            type: 'string',
            nullable: true
        },
        agentName: {
            type: 'string'
        },
        createdAt: {
            type: 'string'
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        overallStatus: {
            type: 'string'
        },
        plateNumber: {
            type: 'string'
        }
    }
} as const;

export const RecentAlertsResponseSchema = {
    type: 'object',
    required: [
        'items'
    ],
    properties: {
        items: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/RecentAlertItemDto'
            }
        }
    }
} as const;

export const RefreshChallengeResponseSchema = {
    type: 'object',
    required: [
        'nonce'
    ],
    properties: {
        nonce: {
            type: 'string'
        }
    }
} as const;

export const RefreshRequestSchema = {
    type: 'object',
    required: [
        'refreshToken'
    ],
    properties: {
        deviceId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        refreshToken: {
            type: 'string'
        }
    }
} as const;

export const RequestDailyLoginRequestSchema = {
    type: 'object',
    required: [
        'badgeId',
        'deviceId'
    ],
    properties: {
        badgeId: {
            type: 'string'
        },
        deviceId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const RequestDailyLoginResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const ResendActivationRequestSchema = {
    type: 'object',
    required: [
        'userId'
    ],
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const ResendActivationResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const RestartSessionRequestSchema = {
    type: 'object',
    required: [
        'userId'
    ],
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const RestartSessionResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const ScanErrorDataSchema = {
    type: 'object',
    description: 'Error detail returned inside the scan response envelope.',
    required: [
        'code',
        'message'
    ],
    properties: {
        code: {
            type: 'string',
            description: 'Machine-readable error code, e.g. `INVALID_IMAGE`.'
        },
        message: {
            type: 'string',
            description: 'Human-readable error description.'
        }
    }
} as const;

export const ScanPlateResponseSchema = {
    type: 'object',
    description: 'Envelope response for `POST /api/v1/scan/plate`.',
    required: [
        'success'
    ],
    properties: {
        data: {
            allOf: [
                {
                    $ref: '#/components/schemas/ScanResultData'
                }
            ],
            nullable: true
        },
        error: {
            allOf: [
                {
                    $ref: '#/components/schemas/ScanErrorData'
                }
            ],
            nullable: true
        },
        success: {
            type: 'boolean'
        }
    }
} as const;

export const ScanResultDataSchema = {
    type: 'object',
    description: 'Successful OCR scan result data.',
    required: [
        'plate',
        'raw_text',
        'confidence',
        'format_valid'
    ],
    properties: {
        confidence: {
            type: 'number',
            format: 'float',
            description: 'Tesseract confidence score (0.0 – 1.0).'
        },
        format_valid: {
            type: 'boolean',
            description: 'Whether the normalized plate matches the Cameroon format (XX###XX).'
        },
        plate: {
            type: 'string',
            description: 'Normalized plate text (uppercase, no spaces). Empty if nothing detected.'
        },
        raw_text: {
            type: 'string',
            description: 'Raw text as returned by the OCR engine before normalization.'
        }
    }
} as const;

export const StatusSchema = {
    type: 'string',
    description: 'Shared status across all partner API responses',
    enum: [
        'valid',
        'warning',
        'critical',
        'pending'
    ]
} as const;

export const StatusResultsSchema = {
    type: 'object',
    required: [
        'overall_status',
        'insurance',
        'police',
        'customs',
        'technical'
    ],
    properties: {
        customs: {
            $ref: '#/components/schemas/CustomsStatus'
        },
        insurance: {
            $ref: '#/components/schemas/InsuranceStatus'
        },
        overall_status: {
            $ref: '#/components/schemas/Status'
        },
        police: {
            $ref: '#/components/schemas/PoliceStatus'
        },
        technical: {
            $ref: '#/components/schemas/TechnicalStatus'
        },
        vehicle_image_url: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const SubmissionLocationSchema = {
    type: 'object',
    properties: {
        address: {
            type: 'string',
            nullable: true
        },
        latitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        longitude: {
            type: 'number',
            format: 'double',
            nullable: true
        }
    }
} as const;

export const SubmissionStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'approved',
        'rejected'
    ]
} as const;

export const TechnicalStatusSchema = {
    type: 'object',
    required: [
        'status',
        'defects'
    ],
    properties: {
        defects: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        expiry_date: {
            type: 'string',
            nullable: true
        },
        last_inspection_date: {
            type: 'string',
            nullable: true
        },
        mileage: {
            type: 'integer',
            format: 'int64',
            nullable: true
        },
        notes: {
            type: 'string',
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/Status'
        }
    }
} as const;

export const TerminateSessionRequestSchema = {
    type: 'object',
    required: [
        'userId'
    ],
    properties: {
        userId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const TerminateSessionResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const TopAgentDtoSchema = {
    type: 'object',
    required: [
        'agentId',
        'agentName',
        'organizationName',
        'controlsCount',
        'isOnline'
    ],
    properties: {
        agentId: {
            type: 'string',
            format: 'uuid'
        },
        agentName: {
            type: 'string'
        },
        controlsCount: {
            type: 'integer',
            format: 'int64'
        },
        isOnline: {
            type: 'boolean'
        },
        organizationName: {
            type: 'string'
        }
    }
} as const;

export const TopAgentsResponseSchema = {
    type: 'object',
    required: [
        'range',
        'agents'
    ],
    properties: {
        agents: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TopAgentDto'
            }
        },
        range: {
            $ref: '#/components/schemas/DashboardRange'
        }
    }
} as const;

export const UpdateLocationRequestSchema = {
    type: 'object',
    required: [
        'latitude',
        'longitude'
    ],
    properties: {
        latitude: {
            type: 'number',
            format: 'double'
        },
        longitude: {
            type: 'number',
            format: 'double'
        }
    }
} as const;

export const UpdateLocationResponseSchema = {
    type: 'object',
    required: [
        'message'
    ],
    properties: {
        message: {
            type: 'string'
        }
    }
} as const;

export const UpdateUserRequestSchema = {
    type: 'object',
    description: 'Request for PATCH /admin/users/:id (update)',
    properties: {
        badgeId: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        fullName: {
            type: 'string',
            nullable: true
        },
        organizationId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        phoneNumber: {
            type: 'string',
            nullable: true
        },
        role: {
            allOf: [
                {
                    $ref: '#/components/schemas/UserRole'
                }
            ],
            nullable: true
        },
        status: {
            allOf: [
                {
                    $ref: '#/components/schemas/UserStatus'
                }
            ],
            nullable: true
        },
        username: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const UploadResponseSchema = {
    type: 'object',
    required: [
        'message',
        'submission_id'
    ],
    properties: {
        message: {
            type: 'string'
        },
        submission_id: {
            type: 'string'
        }
    }
} as const;

export const UserProfileSchema = {
    type: 'object',
    description: 'Response for GET /users/me',
    required: [
        'id',
        'username',
        'name',
        'role',
        'status',
        'isActive'
    ],
    properties: {
        avatarInitials: {
            type: 'string',
            nullable: true
        },
        badgeId: {
            type: 'string',
            nullable: true
        },
        email: {
            type: 'string',
            nullable: true
        },
        id: {
            type: 'string',
            format: 'uuid'
        },
        isActive: {
            type: 'boolean'
        },
        lastRevokedAt: {
            type: 'string',
            format: 'date-time',
            nullable: true
        },
        name: {
            type: 'string'
        },
        organization: {
            type: 'string',
            nullable: true
        },
        organizationId: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        phoneNumber: {
            type: 'string',
            nullable: true
        },
        role: {
            $ref: '#/components/schemas/UserRole'
        },
        sessionStatus: {
            allOf: [
                {
                    $ref: '#/components/schemas/DeviceStatus'
                }
            ],
            nullable: true
        },
        status: {
            $ref: '#/components/schemas/UserStatus'
        },
        username: {
            type: 'string'
        }
    }
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: [
        'admin',
        'agent',
        'manager'
    ]
} as const;

export const UserStatusSchema = {
    type: 'string',
    enum: [
        'PENDING_ACTIVATION',
        'ACTIVE',
        'SUSPENDED'
    ]
} as const;

export const VehicleInfoSchema = {
    type: 'object',
    required: [
        'brand',
        'model',
        'year',
        'chassis_number',
        'owner'
    ],
    properties: {
        brand: {
            type: 'string'
        },
        chassis_number: {
            type: 'string'
        },
        color: {
            type: 'string',
            nullable: true
        },
        engine_power: {
            type: 'string',
            nullable: true
        },
        fuel_type: {
            type: 'string',
            nullable: true
        },
        model: {
            type: 'string'
        },
        owner: {
            $ref: '#/components/schemas/OwnerInfo'
        },
        year: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const VehicleSearchRequestSchema = {
    type: 'object',
    required: [
        'plate'
    ],
    properties: {
        address: {
            type: 'string',
            nullable: true
        },
        agent_id: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        latitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        longitude: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        organization_id: {
            type: 'string',
            format: 'uuid',
            nullable: true
        },
        plate: {
            type: 'string'
        }
    }
} as const;

export const VehicleSearchResultSchema = {
    type: 'object',
    required: [
        'plate_number',
        'vehicle',
        'status_results'
    ],
    properties: {
        confidence: {
            type: 'number',
            format: 'double',
            nullable: true
        },
        identification_mode: {
            allOf: [
                {
                    $ref: '#/components/schemas/IdentificationMode'
                }
            ],
            nullable: true
        },
        plate_number: {
            type: 'string'
        },
        status_results: {
            $ref: '#/components/schemas/StatusResults'
        },
        vehicle: {
            $ref: '#/components/schemas/VehicleInfo'
        }
    }
} as const;

export const VerifyDailyLoginRequestSchema = {
    type: 'object',
    required: [
        'badgeId',
        'activationCode',
        'deviceId'
    ],
    properties: {
        activationCode: {
            type: 'string'
        },
        badgeId: {
            type: 'string'
        },
        deviceId: {
            type: 'string',
            format: 'uuid'
        }
    }
} as const;

export const VerifyDailyLoginResponseSchema = {
    type: 'object',
    required: [
        'accessToken',
        'shiftEnd'
    ],
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string',
            nullable: true
        },
        shiftEnd: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const VerifyRefreshRequestSchema = {
    type: 'object',
    required: [
        'refreshToken',
        'deviceId',
        'signedNonce'
    ],
    properties: {
        deviceId: {
            type: 'string',
            format: 'uuid'
        },
        refreshToken: {
            type: 'string'
        },
        signedNonce: {
            type: 'string'
        }
    }
} as const;

export const VerifyRefreshResponseSchema = {
    type: 'object',
    required: [
        'accessToken'
    ],
    properties: {
        accessToken: {
            type: 'string'
        }
    }
} as const;
