// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type ActionType = 'check' | 'flag' | 'citation' | 'impound' | 'release';

export type ActivateRequest = {
    activationCode: string;
    badgeId: string;
    deviceId: string;
    publicKeyBase64: string;
};

export type ActivateResponse = {
    accessToken: string;
    refreshToken: string;
    user: UserProfile;
};

export type ActivityData = {
    count: number;
    hour: string;
};

export type ActivityFeedItemDto = {
    agentName: string;
    createdAt: string;
    id: string;
    overallStatus: string;
    plateNumber: string;
};

export type ActivityFeedResponse = {
    items: Array<ActivityFeedItemDto>;
};

export type AgentLocationDto = {
    agentId: string;
    agentName: string;
    lastUpdated: string;
    latitude: number;
    longitude: number;
};

export type AppErrorResponse = {
    code: ErrorCode;
    message: string;
};

export type AuthResponse = {
    accessToken: string;
    refreshToken: string;
    user: UserProfile;
};

export type ControlAction = {
    action_type: ActionType;
    description?: string | null;
    timestamp: string;
};

export type ControlActivityPoint = {
    count: number;
    label: string;
};

export type ControlActivityResponse = {
    range: DashboardRange;
    series: Array<ControlActivityPoint>;
};

export type ControlLocation = {
    address?: string | null;
    latitude?: number | null;
    longitude?: number | null;
};

export type ControlResults = {
    customs_status: Status;
    insurance: Status;
    registration: Status;
    technical_inspection: Status;
    wanted_status: Status;
};

export type CreateControlRequest = {
    address?: string | null;
    agent_id: string;
    identification_mode: IdentificationMode;
    latitude?: number | null;
    longitude?: number | null;
    notes?: string | null;
    ocr_confidence?: number | null;
    organization_id: string;
    plate_number: string;
    results: ControlResults;
};

export type CreateControlResponse = {
    id: string;
    message: string;
};

/**
 * Request payload for creating a new pending submission
 */
export type CreatePendingSubmissionRequest = {
    agentId: string;
    backImageUrl: string;
    frontImageUrl: string;
    latitude?: number | null;
    longitude?: number | null;
    notes?: string | null;
    plateNumber: string;
};

export type CustomsStatus = {
    declaration_number?: string | null;
    import_date?: string | null;
    is_cleared: boolean;
    notes?: string | null;
    status: Status;
};

export type DashboardRange = '24h' | '7d' | '30d';

export type DashboardStats = {
    activeAlerts: number;
    activity24h: Array<ActivityData>;
    liveAgents: Array<AgentLocationDto>;
    onlineAgents: number;
    organizationsCount: number;
    pendingSubmissions: number;
    todayControls: number;
    totalVehicles: number;
};

/**
 * Response after approved and enters vehicle data
 */
export type DataEntryResponse = {
    message: string;
    /**
     * Plate number that was added to the external registry
     */
    plate_number: string;
    submission_id: string;
};

export type DeviceStatus = 'PENDING' | 'ACTIVE' | 'INACTIVE' | 'REVOKED' | 'SUSPENDED';

export type ErrorCode = 'UNAUTHORIZED' | 'FORBIDDEN' | 'DATABASE_ERROR' | 'NOT_FOUND' | 'BAD_REQUEST' | 'TOO_MANY_REQUESTS' | 'EXTERNAL_API_FAILURE' | 'INTERNAL_ERROR';

/**
 * How the plate was identified by the agent
 */
export type IdentificationMode = 'manual' | 'photo' | 'live';

export type ImageUploadRequest = {
    image: Blob | File;
};

export type InsuranceStatus = {
    coverage_type?: string | null;
    expiry_date?: string | null;
    notes?: string | null;
    policy_number?: string | null;
    provider?: string | null;
    status: Status;
};

export type ListControlResponse = {
    actions: Array<ControlAction>;
    agent_id: string;
    agent_name?: string | null;
    confidence?: number | null;
    id: string;
    identification_mode: IdentificationMode;
    location: ControlLocation;
    notes?: string | null;
    organization_id: string;
    plate_number: string;
    results: ControlResults;
    status: Status;
    timestamp: string;
    vehicle?: VehicleInfo | null;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type Organization = {
    id: string;
    name: string;
    orgType: OrganizationType;
    region?: string | null;
};

export type OrganizationType = 'police' | 'customs' | 'bordercontrol' | 'other';

export type OwnerInfo = {
    address?: string | null;
    name: string;
    national_id?: string | null;
};

export type PagedControlsResponse = {
    items: Array<ListControlResponse>;
    page: number;
    page_size: number;
    total: number;
};

/**
 * Lightweight list item for admin dashboard
 */
export type PendingSubmissionListItem = {
    agent_name?: string | null;
    id: string;
    plate_number: string;
    status: SubmissionStatus;
    submitted_at: string;
};

/**
 * Detailed view of a pending submission (for admin review)
 */
export type PendingSubmissionRequest = {
    admin_note?: string | null;
    agent_id: string;
    agent_name?: string | null;
    /**
     * URL or Base64 of back image
     */
    back_image_url: string;
    /**
     * URL or Base64 of front image
     */
    front_image_url: string;
    id: string;
    location?: SubmissionLocation | null;
    notes?: string | null;
    plate_number: string;
    reviewed_at?: string | null;
    reviewed_by?: string | null;
    status: SubmissionStatus;
    submitted_at: string;
};

export type PoliceStatus = {
    is_stolen: boolean;
    is_wanted: boolean;
    notes?: string | null;
    report_date?: string | null;
    report_number?: string | null;
    status: Status;
};

/**
 * Request for POST /admin/users (provisioning)
 */
export type ProvisionUserRequest = {
    badgeId?: string | null;
    email?: string | null;
    fullName: string;
    organizationId: string;
    phoneNumber: string;
    role: UserRole;
    username: string;
};

export type RecentAlertItemDto = {
    address?: string | null;
    agentName: string;
    createdAt: string;
    id: string;
    overallStatus: string;
    plateNumber: string;
};

export type RecentAlertsResponse = {
    items: Array<RecentAlertItemDto>;
};

export type RefreshChallengeResponse = {
    nonce: string;
};

export type RefreshRequest = {
    deviceId?: string | null;
    refreshToken: string;
};

export type RequestDailyLoginRequest = {
    badgeId: string;
    deviceId: string;
};

export type RequestDailyLoginResponse = {
    message: string;
};

export type ResendActivationRequest = {
    userId: string;
};

export type ResendActivationResponse = {
    message: string;
};

export type RestartSessionRequest = {
    userId: string;
};

export type RestartSessionResponse = {
    message: string;
};

/**
 * Error detail returned inside the scan response envelope.
 */
export type ScanErrorData = {
    /**
     * Machine-readable error code, e.g. `INVALID_IMAGE`.
     */
    code: string;
    /**
     * Human-readable error description.
     */
    message: string;
};

/**
 * Envelope response for `POST /api/v1/scan/plate`.
 */
export type ScanPlateResponse = {
    data?: ScanResultData | null;
    error?: ScanErrorData | null;
    success: boolean;
};

/**
 * Successful OCR scan result data.
 */
export type ScanResultData = {
    /**
     * Tesseract confidence score (0.0 – 1.0).
     */
    confidence: number;
    /**
     * Whether the normalized plate matches the Cameroon format (XX###XX).
     */
    format_valid: boolean;
    /**
     * Normalized plate text (uppercase, no spaces). Empty if nothing detected.
     */
    plate: string;
    /**
     * Raw text as returned by the OCR engine before normalization.
     */
    raw_text: string;
};

/**
 * Shared status across all partner API responses
 */
export type Status = 'valid' | 'warning' | 'critical' | 'pending';

export type StatusResults = {
    customs: CustomsStatus;
    insurance: InsuranceStatus;
    overall_status: Status;
    police: PoliceStatus;
    technical: TechnicalStatus;
    vehicle_image_url?: string | null;
};

export type SubmissionLocation = {
    address?: string | null;
    latitude?: number | null;
    longitude?: number | null;
};

export type SubmissionStatus = 'pending' | 'approved' | 'rejected';

export type TechnicalStatus = {
    defects: Array<string>;
    expiry_date?: string | null;
    last_inspection_date?: string | null;
    mileage?: number | null;
    notes?: string | null;
    status: Status;
};

export type TerminateSessionRequest = {
    userId: string;
};

export type TerminateSessionResponse = {
    message: string;
};

export type TopAgentDto = {
    agentId: string;
    agentName: string;
    controlsCount: number;
    isOnline: boolean;
    organizationName: string;
};

export type TopAgentsResponse = {
    agents: Array<TopAgentDto>;
    range: DashboardRange;
};

export type UpdateLocationRequest = {
    latitude: number;
    longitude: number;
};

export type UpdateLocationResponse = {
    message: string;
};

/**
 * Request for PATCH /admin/users/:id (update)
 */
export type UpdateUserRequest = {
    badgeId?: string | null;
    email?: string | null;
    fullName?: string | null;
    organizationId?: string | null;
    phoneNumber?: string | null;
    role?: UserRole | null;
    status?: UserStatus | null;
    username?: string | null;
};

export type UploadResponse = {
    message: string;
    submission_id: string;
};

/**
 * Response for GET /users/me
 */
export type UserProfile = {
    avatarInitials?: string | null;
    badgeId?: string | null;
    email?: string | null;
    id: string;
    isActive: boolean;
    lastRevokedAt?: string | null;
    name: string;
    organization?: string | null;
    organizationId?: string | null;
    phoneNumber?: string | null;
    role: UserRole;
    sessionStatus?: DeviceStatus | null;
    status: UserStatus;
    username: string;
};

export type UserRole = 'admin' | 'agent' | 'manager';

export type UserStatus = 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';

export type VehicleInfo = {
    brand: string;
    chassis_number: string;
    color?: string | null;
    engine_power?: string | null;
    fuel_type?: string | null;
    model: string;
    owner: OwnerInfo;
    year: number;
};

export type VehicleSearchRequest = {
    address?: string | null;
    agent_id?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    organization_id?: string | null;
    plate: string;
};

export type VehicleSearchResult = {
    confidence?: number | null;
    identification_mode?: IdentificationMode | null;
    plate_number: string;
    status_results: StatusResults;
    vehicle: VehicleInfo;
};

export type VerifyDailyLoginRequest = {
    activationCode: string;
    badgeId: string;
    deviceId: string;
};

export type VerifyDailyLoginResponse = {
    accessToken: string;
    refreshToken?: string | null;
    shiftEnd: number;
};

export type VerifyRefreshRequest = {
    deviceId: string;
    refreshToken: string;
    signedNonce: string;
};

export type VerifyRefreshResponse = {
    accessToken: string;
};

export type GetControlsPagedData = {
    body?: never;
    path?: never;
    query?: {
        start_date?: string | null;
        end_date?: string | null;
        agent_id?: string | null;
        organization_id?: string | null;
        status?: Status | null;
        plate?: string | null;
        q?: string | null;
        page?: number | null;
        page_size?: number | null;
    };
    url: '/api/v1/admin/controls/paged';
};

export type GetControlsPagedErrors = {
    /**
     * Invalid request
     */
    400: AppErrorResponse;
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetControlsPagedError = GetControlsPagedErrors[keyof GetControlsPagedErrors];

export type GetControlsPagedResponses = {
    /**
     * Paged control records
     */
    200: PagedControlsResponse;
};

export type GetControlsPagedResponse = GetControlsPagedResponses[keyof GetControlsPagedResponses];

export type ListOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/organizations';
};

export type ListOrganizationsErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Forbidden
     */
    403: AppErrorResponse;
};

export type ListOrganizationsError = ListOrganizationsErrors[keyof ListOrganizationsErrors];

export type ListOrganizationsResponses = {
    /**
     * Organizations retrieved successfully
     */
    200: Array<Organization>;
};

export type ListOrganizationsResponse = ListOrganizationsResponses[keyof ListOrganizationsResponses];

export type ResendActivationCodeData = {
    body: ResendActivationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/resend-activation-code';
};

export type ResendActivationCodeErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type ResendActivationCodeError = ResendActivationCodeErrors[keyof ResendActivationCodeErrors];

export type ResendActivationCodeResponses = {
    /**
     * Activation code sent
     */
    201: ResendActivationResponse;
};

export type ResendActivationCodeResponse = ResendActivationCodeResponses[keyof ResendActivationCodeResponses];

export type RestartSessionData = {
    body: RestartSessionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/restart-session';
};

export type RestartSessionErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type RestartSessionError = RestartSessionErrors[keyof RestartSessionErrors];

export type RestartSessionResponses = {
    /**
     * Session restarted
     */
    200: RestartSessionResponse;
};

export type RestartSessionResponse2 = RestartSessionResponses[keyof RestartSessionResponses];

export type GetDashboardStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/stats';
};

export type GetDashboardStatsErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetDashboardStatsError = GetDashboardStatsErrors[keyof GetDashboardStatsErrors];

export type GetDashboardStatsResponses = {
    /**
     * Dashboard statistics retrieved successfully
     */
    200: DashboardStats;
};

export type GetDashboardStatsResponse = GetDashboardStatsResponses[keyof GetDashboardStatsResponses];

export type ListPendingSubmissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/submissions';
};

export type ListPendingSubmissionsErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
};

export type ListPendingSubmissionsError = ListPendingSubmissionsErrors[keyof ListPendingSubmissionsErrors];

export type ListPendingSubmissionsResponses = {
    /**
     * List of pending submissions
     */
    200: Array<PendingSubmissionListItem>;
};

export type ListPendingSubmissionsResponse = ListPendingSubmissionsResponses[keyof ListPendingSubmissionsResponses];

export type GetPendingSubmissionData = {
    body?: never;
    path: {
        /**
         * Submission UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/submissions/{id}';
};

export type GetPendingSubmissionErrors = {
    /**
     * Submission not found
     */
    404: AppErrorResponse;
};

export type GetPendingSubmissionError = GetPendingSubmissionErrors[keyof GetPendingSubmissionErrors];

export type GetPendingSubmissionResponses = {
    /**
     * Submission details
     */
    200: PendingSubmissionRequest;
};

export type GetPendingSubmissionResponse = GetPendingSubmissionResponses[keyof GetPendingSubmissionResponses];

export type TerminateSessionData = {
    body: TerminateSessionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/terminate-session';
};

export type TerminateSessionErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type TerminateSessionError = TerminateSessionErrors[keyof TerminateSessionErrors];

export type TerminateSessionResponses = {
    /**
     * Session terminated
     */
    200: TerminateSessionResponse;
};

export type TerminateSessionResponse2 = TerminateSessionResponses[keyof TerminateSessionResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type ListUsersErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Forbidden
     */
    403: AppErrorResponse;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Users retrieved successfully
     */
    200: Array<UserProfile>;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type ProvisionUserData = {
    body: ProvisionUserRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/users';
};

export type ProvisionUserErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Forbidden
     */
    403: AppErrorResponse;
};

export type ProvisionUserError = ProvisionUserErrors[keyof ProvisionUserErrors];

export type ProvisionUserResponses = {
    /**
     * User provisioned successfully
     */
    201: UserProfile;
};

export type ProvisionUserResponse = ProvisionUserResponses[keyof ProvisionUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Forbidden
     */
    403: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * User deleted successfully
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{id}';
};

export type GetUserErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Forbidden
     */
    403: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User retrieved successfully
     */
    200: UserProfile;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: UpdateUserRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/admin/users/{id}';
};

export type UpdateUserErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Forbidden
     */
    403: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * User updated successfully
     */
    200: UserProfile;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ActivateDeviceData = {
    body: ActivateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/activate';
};

export type ActivateDeviceErrors = {
    /**
     * Bad request
     */
    400: AppErrorResponse;
    /**
     * User not found
     */
    404: AppErrorResponse;
};

export type ActivateDeviceError = ActivateDeviceErrors[keyof ActivateDeviceErrors];

export type ActivateDeviceResponses = {
    /**
     * Activation successful
     */
    200: ActivateResponse;
};

export type ActivateDeviceResponse = ActivateDeviceResponses[keyof ActivateDeviceResponses];

export type LoginUserData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginUserErrors = {
    /**
     * Invalid credentials
     */
    401: AppErrorResponse;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Login successful
     */
    200: AuthResponse;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type RequestRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RequestRefreshErrors = {
    /**
     * Invalid or expired refresh token
     */
    401: AppErrorResponse;
};

export type RequestRefreshError = RequestRefreshErrors[keyof RequestRefreshErrors];

export type RequestRefreshResponses = {
    /**
     * Challenge nonce issued
     */
    200: RefreshChallengeResponse;
};

export type RequestRefreshResponse = RequestRefreshResponses[keyof RequestRefreshResponses];

export type VerifyRefreshData = {
    body: VerifyRefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh/verify';
};

export type VerifyRefreshErrors = {
    /**
     * Signature verification failed
     */
    401: AppErrorResponse;
};

export type VerifyRefreshError = VerifyRefreshErrors[keyof VerifyRefreshErrors];

export type VerifyRefreshResponses = {
    /**
     * New access token issued
     */
    200: VerifyRefreshResponse;
};

export type VerifyRefreshResponse2 = VerifyRefreshResponses[keyof VerifyRefreshResponses];

export type RequestDailyLoginData = {
    body: RequestDailyLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/request-daily-login';
};

export type RequestDailyLoginErrors = {
    /**
     * Bad request — missing or invalid fields
     */
    400: AppErrorResponse;
    /**
     * User or device is suspended
     */
    401: AppErrorResponse;
    /**
     * User or device not found
     */
    404: AppErrorResponse;
    /**
     * Too many OTP requests
     */
    429: AppErrorResponse;
};

export type RequestDailyLoginError = RequestDailyLoginErrors[keyof RequestDailyLoginErrors];

export type RequestDailyLoginResponses = {
    /**
     * OTP sent successfully
     */
    201: RequestDailyLoginResponse;
};

export type RequestDailyLoginResponse2 = RequestDailyLoginResponses[keyof RequestDailyLoginResponses];

export type VerifyDailyLoginData = {
    body: VerifyDailyLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/verify-daily-login';
};

export type VerifyDailyLoginErrors = {
    /**
     * Bad request — missing or invalid fields
     */
    400: AppErrorResponse;
    /**
     * Invalid OTP, expired, or device suspended
     */
    401: AppErrorResponse;
    /**
     * User or device not found
     */
    404: AppErrorResponse;
};

export type VerifyDailyLoginError = VerifyDailyLoginErrors[keyof VerifyDailyLoginErrors];

export type VerifyDailyLoginResponses = {
    /**
     * Login successful
     */
    200: VerifyDailyLoginResponse;
};

export type VerifyDailyLoginResponse2 = VerifyDailyLoginResponses[keyof VerifyDailyLoginResponses];

export type GetControlsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter controls from this date (inclusive)
         */
        start_date?: string | null;
        /**
         * Filter controls until this date (inclusive)
         */
        end_date?: string | null;
        /**
         * Filter controls by agent UUID
         */
        agent_id?: string | null;
        /**
         * Filter controls by status
         */
        status?: Status | null;
        /**
         * Filter controls by plate number
         */
        plate?: string | null;
    };
    url: '/api/v1/controls';
};

export type GetControlsErrors = {
    /**
     * Invalid request
     */
    400: AppErrorResponse;
    /**
     * Not found
     */
    404: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetControlsError = GetControlsErrors[keyof GetControlsErrors];

export type GetControlsResponses = {
    /**
     * List of control records
     */
    200: Array<ListControlResponse>;
};

export type GetControlsResponse = GetControlsResponses[keyof GetControlsResponses];

export type CreateControlData = {
    body: CreateControlRequest;
    path?: never;
    query?: never;
    url: '/api/v1/controls';
};

export type CreateControlErrors = {
    /**
     * Invalid request
     */
    400: AppErrorResponse;
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type CreateControlError = CreateControlErrors[keyof CreateControlErrors];

export type CreateControlResponses = {
    /**
     * Control created
     */
    201: CreateControlResponse;
};

export type CreateControlResponse2 = CreateControlResponses[keyof CreateControlResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthResponses = {
    /**
     * Service is healthy
     */
    200: string;
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type PhotoPlateData = {
    body: ImageUploadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/photo/plate';
};

export type PhotoPlateErrors = {
    /**
     * Invalid or missing image
     */
    400: ScanPlateResponse;
    /**
     * Unsupported media type
     */
    415: ScanPlateResponse;
    /**
     * Internal OCR error
     */
    500: ScanPlateResponse;
};

export type PhotoPlateError = PhotoPlateErrors[keyof PhotoPlateErrors];

export type PhotoPlateResponses = {
    /**
     * OCR result (photo capture)
     */
    200: ScanPlateResponse;
};

export type PhotoPlateResponse = PhotoPlateResponses[keyof PhotoPlateResponses];

export type ScanPlateData = {
    body: ImageUploadRequest;
    path?: never;
    query?: never;
    url: '/api/v1/scan/plate';
};

export type ScanPlateErrors = {
    /**
     * Invalid or missing image
     */
    400: ScanPlateResponse;
    /**
     * Unsupported media type
     */
    415: ScanPlateResponse;
    /**
     * Internal OCR error
     */
    500: ScanPlateResponse;
};

export type ScanPlateError = ScanPlateErrors[keyof ScanPlateErrors];

export type ScanPlateResponses = {
    /**
     * OCR result (may have low confidence)
     */
    200: ScanPlateResponse;
};

export type ScanPlateResponse2 = ScanPlateResponses[keyof ScanPlateResponses];

export type GetControlActivityData = {
    body?: never;
    path?: never;
    query?: {
        range?: DashboardRange | null;
    };
    url: '/api/v1/stats/activity';
};

export type GetControlActivityErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetControlActivityError = GetControlActivityErrors[keyof GetControlActivityErrors];

export type GetControlActivityResponses = {
    /**
     * Control activity series retrieved successfully
     */
    200: ControlActivityResponse;
};

export type GetControlActivityResponse = GetControlActivityResponses[keyof GetControlActivityResponses];

export type GetActivityFeedData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number | null;
    };
    url: '/api/v1/stats/activity-feed';
};

export type GetActivityFeedErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetActivityFeedError = GetActivityFeedErrors[keyof GetActivityFeedErrors];

export type GetActivityFeedResponses = {
    /**
     * Activity feed retrieved successfully
     */
    200: ActivityFeedResponse;
};

export type GetActivityFeedResponse = GetActivityFeedResponses[keyof GetActivityFeedResponses];

export type GetRecentAlertsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number | null;
    };
    url: '/api/v1/stats/recent-alerts';
};

export type GetRecentAlertsErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetRecentAlertsError = GetRecentAlertsErrors[keyof GetRecentAlertsErrors];

export type GetRecentAlertsResponses = {
    /**
     * Recent alerts retrieved successfully
     */
    200: RecentAlertsResponse;
};

export type GetRecentAlertsResponse = GetRecentAlertsResponses[keyof GetRecentAlertsResponses];

export type GetTopAgentsData = {
    body?: never;
    path?: never;
    query?: {
        range?: DashboardRange | null;
        limit?: number | null;
    };
    url: '/api/v1/stats/top-agents';
};

export type GetTopAgentsErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetTopAgentsError = GetTopAgentsErrors[keyof GetTopAgentsErrors];

export type GetTopAgentsResponses = {
    /**
     * Top agents retrieved successfully
     */
    200: TopAgentsResponse;
};

export type GetTopAgentsResponse = GetTopAgentsResponses[keyof GetTopAgentsResponses];

export type UpdateLocationData = {
    body: UpdateLocationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/location';
};

export type UpdateLocationErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type UpdateLocationError = UpdateLocationErrors[keyof UpdateLocationErrors];

export type UpdateLocationResponses = {
    /**
     * Location updated successfully
     */
    200: UpdateLocationResponse;
};

export type UpdateLocationResponse2 = UpdateLocationResponses[keyof UpdateLocationResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetUserProfileErrors = {
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type GetUserProfileError = GetUserProfileErrors[keyof GetUserProfileErrors];

export type GetUserProfileResponses = {
    /**
     * Current user profile
     */
    200: UserProfile;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type SubmitVehicleV1Data = {
    body: CreatePendingSubmissionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/vehicles/pending';
};

export type SubmitVehicleV1Errors = {
    /**
     * Invalid request
     */
    400: AppErrorResponse;
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type SubmitVehicleV1Error = SubmitVehicleV1Errors[keyof SubmitVehicleV1Errors];

export type SubmitVehicleV1Responses = {
    /**
     * Submission accepted for review
     */
    202: DataEntryResponse;
};

export type SubmitVehicleV1Response = SubmitVehicleV1Responses[keyof SubmitVehicleV1Responses];

export type SearchVehicleV1Data = {
    body: VehicleSearchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/vehicles/search';
};

export type SearchVehicleV1Errors = {
    /**
     * Invalid plate format
     */
    400: AppErrorResponse;
    /**
     * Unauthorized
     */
    401: AppErrorResponse;
    /**
     * Plate not found in registry
     */
    404: AppErrorResponse;
    /**
     * Internal server error
     */
    500: AppErrorResponse;
};

export type SearchVehicleV1Error = SearchVehicleV1Errors[keyof SearchVehicleV1Errors];

export type SearchVehicleV1Responses = {
    /**
     * Vehicle found with status results
     */
    200: VehicleSearchResult;
};

export type SearchVehicleV1Response = SearchVehicleV1Responses[keyof SearchVehicleV1Responses];
